output "db_id" {
  description = "Database cluster ID"
  value       = ovh_cloud_project_database.postgresql.id
}

output "db_host" {
  description = "Database host"
  value       = ovh_cloud_project_database.postgresql.endpoints[0].domain
}

output "db_port" {
  description = "Database port"
  value       = ovh_cloud_project_database.postgresql.endpoints[0].port
}

output "db_uri" {
  description = "Database connection URI"
  value       = ovh_cloud_project_database.postgresql.endpoints[0].uri
  sensitive   = true
}

output "db_user_password" {
  description = "Database user password (generated by OVH)"
  value       = ovh_cloud_project_database_user.app.password
  sensitive   = true
}
